import About from '@/components/about'
import Banner from '@/components/banner'
import ContactForm from '@/components/contactForm'
import Footer from '@/components/footer'
import Projects from '@/components/projects'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Kelsy-Anne</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./favicon.ico" />
      </Head>

      <main>
        <Banner />
        <About />
        <Projects />
        <ContactForm />
        <Footer />
      </main>
      
    </>
  )
}
